# -*- coding: utf-8 -*-
"""
Builds two JS data files that power images and detailed descriptions:
  data/images.js      → window.IMAGES_BY_ID  = { "1358": ["file1.jpg", ...], ... }
  data/details.js     → window.DETAILS_BY_ID = { "1358": "...опис...", ... }

Re-run this whenever the photo folder or xlsx is updated.
"""
import os
import re
import json
import sys
import io
import pandas as pd

ROOT = os.path.dirname(os.path.abspath(__file__))
IMG_DIR_NAME = '2025-2026-named-top5'
IMG_DIR = os.path.join(ROOT, IMG_DIR_NAME)
XLSX = os.path.join(ROOT, 'Детальна інформація по товарах.xlsx')
OUT_DIR = os.path.join(ROOT, 'data')
os.makedirs(OUT_DIR, exist_ok=True)

# Force utf-8 for stdout (Windows cp1251 default crashes on cyrillic prints)
if sys.stdout.encoding and sys.stdout.encoding.lower() != 'utf-8':
    try:
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
    except Exception:
        pass

ID_RE = re.compile(r'\((\d{3,5})\)')


def natural_key(name):
    """Order so that base.jpg comes before _2.jpg, _3.jpg, etc."""
    base = name.lower()
    m = re.search(r'_(\d+)\.(jpg|jpeg|png|webp)$', base)
    return (0 if m is None else int(m.group(1)),)


def build_images():
    by_id = {}
    if not os.path.isdir(IMG_DIR):
        print(f'IMG_DIR missing: {IMG_DIR}')
        return by_id
    for fname in os.listdir(IMG_DIR):
        if not fname.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')):
            continue
        ids = ID_RE.findall(fname)
        if not ids:
            continue
        # Use the LAST id captured (xlsx style: "Name (1234)") and also
        # support "(1234) Name". We pick last because forms like
        # "Bric a Brac C2R Товари ... (1794)" embed id at the end.
        pid = ids[-1].lstrip('0') or ids[-1]
        # Also store with leading zero forms (some products are coded "0537")
        keys = {pid, ids[-1]}
        for k in keys:
            by_id.setdefault(k, []).append(fname)
    # Sort each list naturally
    for k, files in by_id.items():
        files.sort(key=natural_key)
    return by_id


def build_details():
    by_id = {}
    try:
        df = pd.read_excel(XLSX, header=None)
    except Exception as e:
        print(f'Cannot read xlsx: {e}')
        return by_id
    for _, row in df.iterrows():
        cell = row.iloc[0]
        if not isinstance(cell, str):
            continue
        ids = ID_RE.findall(cell)
        if not ids:
            continue
        pid_raw = ids[0]
        # remove the "(NNNN)" prefix from the description
        text = ID_RE.sub('', cell, count=1).strip().lstrip(',').strip()
        # normalise multi-spaces and bullets
        text = re.sub(r'\r', '', text).strip()
        keys = {pid_raw, pid_raw.lstrip('0') or pid_raw}
        for k in keys:
            if k not in by_id:
                by_id[k] = text
    return by_id


def write_js(path, varname, obj):
    js = f'window.{varname} = ' + json.dumps(obj, ensure_ascii=False, indent=0).replace('\n', '') + ';\n'
    with open(path, 'w', encoding='utf-8') as f:
        f.write(f'// auto-generated by generate_assets.py — do NOT edit\n')
        f.write(js)


def main():
    images = build_images()
    details = build_details()
    write_js(os.path.join(OUT_DIR, 'images.js'), 'IMAGES_BY_ID', images)
    write_js(os.path.join(OUT_DIR, 'details.js'), 'DETAILS_BY_ID', details)
    write_js(os.path.join(OUT_DIR, 'meta.js'), 'IMAGES_DIR', IMG_DIR_NAME)

    print(f'Images: {len(images)} unique product IDs, '
          f'{sum(len(v) for v in images.values())} files total')
    print(f'Details: {len(details)} entries')


if __name__ == '__main__':
    main()
